# Generated by Django 5.2.18 on 2026-10-10 00:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_concepto_domicilio_restrict'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('acciones', '📈 Acciones'), ('auto', '🚗 Auto'), ('inmueble', '🏡 Casa o departamento'), ('cuenta_ahorro', '💰 Cuenta de ahorro'), ('cuenta_inversion', '📊 Cuenta de inversión'), ('afore', '👵 Afore'), ('stock_options', '🧾 Stock options'), ('terreno', '🌄 Terreno'), ('otro', '🎲 Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valor actual')),
                ('fecha_valuacion', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de valuación')),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, help_text='Opcional: si el valor viene de una cuenta (ahorro, inversión, afore).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cuenta')),
                ('domicilio', models.ForeignKey(blank=True, help_text='Opcional: si el activo es un inmueble.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.domicilio')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['-activo', '-valor_actual', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('auto', '🚗 Auto'), ('casa', '🏡 Casa'), ('compra_importante', '🛍️ Compra importante'), ('educacion', '🎓 Educación'), ('fondo_emergencia', '🛟 Fondo de emergencia'), ('regalo', '🎁 Regalo'), ('remodelacion', '🔨 Remodelación'), ('vacaciones', '🏖️ Vacaciones'), ('otro', '🎲 Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='meta de ahorro total')),
                ('ahorro_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ahorro actual')),
                ('meses', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='meses para ahorrar')),
                ('tasa_anual', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tasa de interés anual')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inicio')),
                ('activa', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, help_text='Opcional: la cuenta donde guardas este ahorro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cuenta')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'meta de ahorro',
                'verbose_name_plural': 'metas de ahorro',
                'ordering': ['-activa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SimulacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='crédito total')),
                ('tasa_anual', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tasa de interés anual')),
                ('meses', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='duración en meses')),
                ('comision_apertura', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='comisión por apertura')),
                ('pagos_anticipados', models.JSONField(blank=True, default=dict, help_text='{"<mes>": "<monto>"}', verbose_name='pagos anticipados')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'simulación de crédito',
                'verbose_name_plural': 'simulaciones de crédito',
                'ordering': ['nombre'],
            },
        ),
    ]
