# Generated by Django 5.2.18 on 2026-10-09 07:54

import apps.core.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('zona_horaria', models.CharField(default='America/Monterrey', max_length=64)),
            ],
            options={
                'verbose_name': 'hogar',
                'verbose_name_plural': 'hogares',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', apps.core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('lector', 'Lector')], default='admin', max_length=10)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='core.hogar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuario_email_unico_ci'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('hogar', 'usuario'), name='membresia_unica'),
        ),
    ]
