# Generated by Django 5.2.18 on 2026-10-10 02:30

import apps.importacion.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_concepto_domicilio_restrict'),
        ('core', '0001_initial'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(max_length=255, upload_to=apps.importacion.models.ruta_documento)),
                ('nombre_original', models.CharField(max_length=255, verbose_name='nombre original')),
                ('sha256', models.CharField(max_length=64)),
                ('tipo', models.CharField(blank=True, choices=[('estado_cuenta', 'Estado de cuenta'), ('nomina', 'Recibo de nómina'), ('recibo_servicio', 'Recibo de servicio'), ('otro', 'Otro')], max_length=20)),
                ('emisor', models.CharField(blank=True, max_length=80)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('saldo_al_corte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='saldo al corte')),
                ('paginas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='páginas')),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('por_revisar', 'Por revisar'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado'), ('error', 'Error')], default='subido', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('aviso', models.CharField(blank=True, max_length=255)),
                ('modelo_ia', models.CharField(blank=True, max_length=40, verbose_name='modelo de IA')),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_estimado_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='costo estimado (USD)')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='catalogos.cuenta')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReglaClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('patron', models.CharField(help_text='Palabras que contiene la descripción (sin mayúsculas ni acentos), ej. «oxxo».', max_length=120, verbose_name='patrón')),
                ('emisor', models.CharField(blank=True, help_text='Opcional: aplica solo a documentos de este emisor.', max_length=80)),
                ('es_hormiga', models.BooleanField(blank=True, null=True, verbose_name='hormiga 🐜')),
                ('prioridad', models.PositiveSmallIntegerField(default=100)),
                ('veces_aplicada', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.categoria')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.concepto')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.domicilio')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.persona')),
            ],
            options={
                'verbose_name': 'regla de clasificación',
                'verbose_name_plural': 'reglas de clasificación',
                'ordering': ['prioridad', 'patron'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPropuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('descripcion_original', models.CharField(max_length=255, verbose_name='descripción original')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('pago_deuda', 'Pago de deuda')], max_length=15)),
                ('tipo_ingreso', models.CharField(blank=True, choices=[('salario', 'Salario'), ('aguinaldo', 'Aguinaldo'), ('ptu', 'Utilidades (PTU)'), ('bono', 'Bono'), ('beca', 'Beca'), ('prestamo_recibido', 'Préstamo recibido'), ('reembolso', 'Reembolso'), ('venta', 'Venta'), ('otro', 'Otro')], max_length=20, verbose_name='tipo de ingreso')),
                ('es_extraordinario', models.BooleanField(default=False, verbose_name='extraordinario')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de débito'), ('tarjeta_credito', 'Tarjeta de crédito'), ('domiciliacion', 'Domiciliación')], default='efectivo', max_length=15, verbose_name='método de pago')),
                ('es_hormiga', models.BooleanField(default=False, verbose_name='hormiga 🐜')),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('descartado', 'Descartado')], default='pendiente', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.categoria', verbose_name='categoría')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.concepto')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cuenta')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.cuenta', verbose_name='cuenta destino')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='importacion.documento')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.domicilio')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuesta', to='movimientos.movimiento')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.persona')),
                ('posible_duplicado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='movimientos.movimiento')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='importacion.reglaclasificacion')),
            ],
            options={
                'verbose_name': 'movimiento propuesto',
                'verbose_name_plural': 'movimientos propuestos',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('hogar', 'sha256'), name='documento_unico_por_hogar'),
        ),
    ]
