# Generated by Django 5.2.18 on 2026-10-09 22:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_concepto_valores_sugeridos'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('porcentaje_ahorro', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='% de ahorro')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'plantilla de presupuesto',
                'verbose_name_plural': 'plantillas de presupuesto',
            },
        ),
        migrations.CreateModel(
            name='PlantillaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo_ingreso', models.CharField(choices=[('salario', 'Salario'), ('aguinaldo', 'Aguinaldo'), ('ptu', 'Utilidades (PTU)'), ('bono', 'Bono'), ('beca', 'Beca'), ('prestamo_recibido', 'Préstamo recibido'), ('reembolso', 'Reembolso'), ('venta', 'Venta'), ('otro', 'Otro')], default='salario', max_length=20, verbose_name='tipo de ingreso')),
                ('es_fijo', models.BooleanField(default=True, verbose_name='fijo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.persona')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='presupuesto.plantillapresupuesto')),
            ],
            options={
                'verbose_name': 'ingreso de la plantilla',
                'verbose_name_plural': 'ingresos de la plantilla',
                'ordering': ['-monto', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantillaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_fijo', models.BooleanField(default=False, verbose_name='fijo')),
                ('con_tarjeta', models.BooleanField(default=False, verbose_name='con tarjeta')),
                ('es_hormiga', models.BooleanField(default=False, verbose_name='hormiga 🐜')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=7)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='catalogos.concepto')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='presupuesto.plantillapresupuesto')),
            ],
            options={
                'verbose_name': 'gasto de la plantilla',
                'verbose_name_plural': 'gastos de la plantilla',
                'ordering': ['concepto__categoria__orden', 'concepto__nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('porcentaje_ahorro', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='% de ahorro')),
                ('cerrado', models.BooleanField(default=False)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'presupuesto del mes',
                'verbose_name_plural': 'presupuestos del mes',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMesGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_fijo', models.BooleanField(default=False, verbose_name='fijo')),
                ('con_tarjeta', models.BooleanField(default=False, verbose_name='con tarjeta')),
                ('es_hormiga', models.BooleanField(default=False, verbose_name='hormiga 🐜')),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monto mensual')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='catalogos.concepto')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='presupuesto.presupuestomes')),
            ],
            options={
                'verbose_name': 'gasto del mes',
                'verbose_name_plural': 'gastos del mes',
                'ordering': ['concepto__categoria__orden', 'concepto__nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMesIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo_ingreso', models.CharField(choices=[('salario', 'Salario'), ('aguinaldo', 'Aguinaldo'), ('ptu', 'Utilidades (PTU)'), ('bono', 'Bono'), ('beca', 'Beca'), ('prestamo_recibido', 'Préstamo recibido'), ('reembolso', 'Reembolso'), ('venta', 'Venta'), ('otro', 'Otro')], default='salario', max_length=20, verbose_name='tipo de ingreso')),
                ('es_fijo', models.BooleanField(default=True, verbose_name='fijo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.persona')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='presupuesto.presupuestomes')),
            ],
            options={
                'verbose_name': 'ingreso del mes',
                'verbose_name_plural': 'ingresos del mes',
                'ordering': ['-monto', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='plantillapresupuesto',
            constraint=models.UniqueConstraint(fields=('hogar',), name='plantilla_unica_por_hogar'),
        ),
        migrations.AddConstraint(
            model_name='plantillagasto',
            constraint=models.UniqueConstraint(fields=('plantilla', 'concepto'), name='plantilla_gasto_unico'),
        ),
        migrations.AddConstraint(
            model_name='presupuestomes',
            constraint=models.UniqueConstraint(fields=('hogar', 'anio', 'mes'), name='presupuesto_mes_unico'),
        ),
        migrations.AddConstraint(
            model_name='presupuestomesgasto',
            constraint=models.UniqueConstraint(fields=('presupuesto', 'concepto'), name='presupuesto_mes_gasto_unico'),
        ),
    ]
