# Generated by Django 5.2.18 on 2026-10-09 22:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_concepto_valores_sugeridos'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('pago_deuda', 'Pago de deuda')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('tipo_ingreso', models.CharField(blank=True, choices=[('salario', 'Salario'), ('aguinaldo', 'Aguinaldo'), ('ptu', 'Utilidades (PTU)'), ('bono', 'Bono'), ('beca', 'Beca'), ('prestamo_recibido', 'Préstamo recibido'), ('reembolso', 'Reembolso'), ('venta', 'Venta'), ('otro', 'Otro')], max_length=20, verbose_name='tipo de ingreso')),
                ('es_extraordinario', models.BooleanField(default=False, verbose_name='extraordinario')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de débito'), ('tarjeta_credito', 'Tarjeta de crédito'), ('domiciliacion', 'Domiciliación')], default='efectivo', max_length=15, verbose_name='método de pago')),
                ('es_hormiga', models.BooleanField(default=False, verbose_name='hormiga 🐜')),
                ('notas', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado')], default='manual', max_length=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.categoria', verbose_name='categoría')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.concepto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='catalogos.cuenta')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_entrantes', to='catalogos.cuenta', verbose_name='cuenta destino')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='catalogos.domicilio')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='catalogos.persona')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['hogar', 'fecha'], name='mov_hogar_fecha'), models.Index(fields=['hogar', 'categoria', 'fecha'], name='mov_hogar_categoria_fecha'), models.Index(fields=['hogar', 'cuenta', 'fecha'], name='mov_hogar_cuenta_fecha'), models.Index(fields=['hogar', 'persona'], name='mov_hogar_persona'), models.Index(fields=['hogar', 'domicilio'], name='mov_hogar_domicilio')],
            },
        ),
    ]
