# Generated by Django 5.2.18 on 2026-10-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='importacion.documento'),
        ),
    ]
