# Generated by Django 5.2.18 on 2026-10-09 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60)),
                ('icono', models.CharField(blank=True, max_length=8)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'verbose_name': 'categoría',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('parentesco', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Tarjeta de crédito'), ('prestamo', 'Préstamo / crédito'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión')], max_length=10)),
                ('institucion', models.CharField(blank=True, max_length=80)),
                ('producto', models.CharField(blank=True, max_length=80)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4)),
                ('linea_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tasa_anual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('paga_total_mensual', models.BooleanField(blank=True, null=True)),
                ('dia_corte', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_pago', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('monto_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mensualidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_saldo', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='catalogos.persona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('es_fijo', models.BooleanField(default=False)),
                ('es_hormiga', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='catalogos.categoria')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hogar')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cuenta')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.domicilio')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.persona')),
            ],
            options={
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TasaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.CharField(max_length=80)),
                ('producto', models.CharField(max_length=80)),
                ('tasa_promedio', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fecha_referencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tasa de mercado',
                'verbose_name_plural': 'tasas de mercado',
                'ordering': ['institucion', 'producto'],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'producto'), name='tasa_mercado_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('hogar', 'nombre'), name='categoria_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='domicilio',
            constraint=models.UniqueConstraint(fields=('hogar', 'alias'), name='domicilio_alias_unico'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('hogar', 'nombre'), name='persona_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(fields=('hogar', 'nombre'), name='cuenta_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre', 'domicilio'), name='concepto_unico_por_domicilio', nulls_distinct=False),
        ),
    ]
