# Generated by Django 5.2.18 on 2026-10-09 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conceptos', to='catalogos.categoria'),
        ),
    ]
