# Generated by Django 5.2.18 on 2026-10-09 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_concepto_categoria_restrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Opcional. Se precarga al registrar un movimiento y puedes cambiarlo en cada uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cuenta', verbose_name='cuenta por defecto'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='domicilio',
            field=models.ForeignKey(blank=True, help_text='Opcional. Distingue el mismo concepto en varios domicilios (ej. Luz de Casa Fidel) y se precarga al registrar un movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.domicilio', verbose_name='domicilio por defecto'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Opcional. Se precarga al registrar un movimiento y puedes cambiarlo en cada uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.persona', verbose_name='persona por defecto'),
        ),
    ]
