# Generated by Django 5.2.18 on 2026-10-09 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_concepto_valores_sugeridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='domicilio',
            field=models.ForeignKey(blank=True, help_text='Opcional. Distingue el mismo concepto en varios domicilios (ej. Luz de Casa Fidel) y se precarga al registrar un movimiento.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.domicilio', verbose_name='domicilio por defecto'),
        ),
    ]
